# Generated by Django 3.2.1 on 2021-05-06 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_newusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newusermodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newusermodel',
            name='phoneno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
