# Generated by Django 3.2.1 on 2021-05-06 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_auto_20210506_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newusermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='newusermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user'),
        ),
    ]
